### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by djshuckerow** [Mashape/unirest-python#19]
In Python3.4, I run
$ pip install unirest 
I get the following error:
Downloading/unpacking unirest
  Downloading Unirest-1.1.6.tar.gz
  Running setup.py (path:C:\Users\David\AppData\Local\Temp\pip_build_David\unirest\setup.py) egg_info for package unirest

```
warning: no files found matching '*.txt' under directory 'docs'
```

Downloading/unpacking poster>=0.8.1 (from unirest)
  Downloading poster-0.8.1.tar.gz
  Running setup.py (path:C:\Users\David\AppData\Local\Temp\pip_build_David\poster\setup.py) egg_info for package poster
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\David\AppData\Local\Temp\pip_build_David\poster\setup.py", line 2, in <module>
        import poster
      File "C:\Users\David\AppData\Local\Temp\pip_build_David\poster\poster__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "C:\Users\David\AppData\Local\Temp\pip_build_David\poster\poster\streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\David\AppData\Local\Temp\pip_build_David\poster\setup.py", line 2, in <module>

```
import poster
```

  File "C:\Users\David\AppData\Local\Temp\pip_build_David\poster\poster__init__.py", line 29, in <module>

```
import poster.streaminghttp
```

  File "C:\Users\David\AppData\Local\Temp\pip_build_David\poster\poster\streaminghttp.py", line 61

```
print "send:", repr(value)

            ^
```

SyntaxError: invalid syntax

PS: I'm running Windows 8.1, although this looks like a problem in python2 vs python3 syntax.

**Comment by alexandrevicenzi** [comment]
Yes. It's a problem with poster package. It's only works with Python 2.

A good way to solve this is to remove poster dependency or send a PR to [poster project](https://github.com/JeremyGrosser/python-poster).

**Comment by ygbr** [comment]
+1

**Comment by simudream** [comment]
+1

**Comment by ipeisong** [comment]
+1

**Comment by mrd1no** [comment]
Hi all, I managed to create a working version of poster:
https://github.com/mrd1no/poster-0.8.1-for-Python-3.4

I can also install correctly unirest (I still have some minor issues with StringIO for this library:
builtins.TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str)

**Comment by Shokr** [comment]
+1

**Comment by mikeyhew** [comment]
Still not working as of today:

```bash
$ pip3 install unirest
Collecting unirest
  Downloading Unirest-1.1.7.tar.gz
Collecting poster>=0.8.1 (from unirest)
  Downloading poster-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lk/kgsvgr293l94fhdbnvk1mjx00000gn/T/pip-build-f9rc1vhp/poster/setup.py", line 2, in <module>
        import poster
      File "/private/var/folders/lk/kgsvgr293l94fhdbnvk1mjx00000gn/T/pip-build-f9rc1vhp/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/private/var/folders/lk/kgsvgr293l94fhdbnvk1mjx00000gn/T/pip-build-f9rc1vhp/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1
```

**Comment by alexandrevicenzi** [comment]
@mikeyhew there's always [requests](https://github.com/kennethreitz/requests) to replace unirest

**Comment by mikeyhew** [comment]
@alexandrevicenzi true. That's what I ended up using today.

**Comment by tirkarthi** [comment]
In case anyone needs I have made a fork compatible with Python 3 at https://github.com/tirkarthi/unirest-python . You can use it as a git based dependency. It doesn't work for gzip based files for now.

There is an incompatible dependency poster. You can find a Python 3 fork of the same at https://github.com/tirkarthi/python-poster.

**Comment by QGB** [comment]
Unirest vs requests
