### ISSUE TITLE
Handling of poor connection or failed connections

### ISSUE THREAD

**Issue by TravisJoe** [Mashape/unirest-python#21]
Hello,

I will be honest I am not the most knowledgeable with web communication. I mostly deal with hardware communication like RS232, RS485, CAN and other serial communication often used in embedded systems. This is one thing that attached me to this library, that and simple asynchronous communication. 

My question is I am dealing with a situation with poor and intermittent wireless connections. When using unirest it appears to throw exceptions when it is unable to connect. I don't seem to be able to catch this exception in a way that I can handle it is no internet or timeout, at least not when trying to use the callback function. For now I use a basic function to connect using a normal socket and if it fails I do not try to post data with unirest. 

I know I am probably missing something important due to my lack of experience, so I am asking your thoughts on how I should handle this situation. 

I am using an embedded linux system that is single cored, which is how I found your library since it has non-blocking asynchronous calls. I am using mobile wifi as my communication path to the server.

Any input would be helpful on how to best achieve a more robust solution. 

Thanks

**Comment by TravisJoe** [comment]
Sorry for the long delay. The code and functionality was manageable on the project so we moved forward focusing on other areas, but now I am back trying to clean up some things.

It appears that the socket timeout is not being caught by the unirest library. This is not the end of the world, but it would be nice if the exception was caught and easier to handle. Because I am using the Asynchronous feature I am not sure how I should handle it since it starts a new thread for the callback function.

This is the exception in the terminal.
```shell
Exception in thread Thread-98:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/unirest/__init__.py", line 93, in __request
    response = urllib2.urlopen(req, timeout=_timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/poster/streaminghttp.py", line 142, in http_open
    return self.do_open(StreamingHTTPConnection, req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```

I have found several potential solutions,
```python
try:
    response = urllib2.urlopen("http://google.com", None, 2.5)
except URLError, e:
    print "Oops, timed out?"
except socket.timeout:
    print "Timed out!"
```
and
```python
try:
    urllib2.urlopen("http://example.com", timeout = 1)
except urllib2.URLError as e:
    print type(e)    #not catch
except socket.timeout as e:
    print type(e)    #catched
```

Here are clips of my software

```python
    def _sendPacket(self,packetData):
        try:
            self.log.info('WEB - Sending packet')
            unirest.post(self.POST_URL_STATUS, headers=self.HEADERS, params=packetData, callback=self._callBack)
        except:
            self.log.error('WEB - Failed to send packet')
```

```python
    def _callBack(self, response):
        self.log.info('WEB - Web call back complete')
        self.lastCallBackTime = time.time()
```

**Comment by TravisJoe** [comment]
From my looking around and testing unirest is only catching some of the issues with

```python
except urllib2.HTTPError, e:
            response = e
```

And you might need to add (see below) after the HTTPError to catch anything else the urllib2 might throw. 

```python
except urllib2.URLError as e:
    response = e
````

**Comment by vshivam** [comment]
@TravisJoe Setting `response = e` will not work in case of urllib2.URLError exceptions because `e` does not have any response code and headers. You'll need to return a custom response. 

I had fixed the issue on my fork[1] with a custom response. The README there also explains the issue and the fix. Just putting it out here if anyone else faces the same issue. 

[1] https://github.com/vshivam/unirest-python/

**Comment by hutchic** [comment]
@vshivam if you haven't already you should submit a PR

**Comment by vshivam** [comment]
@hutchic I had but received no replies for about a year. So, closed it and explained the fix in my fork.

**Comment by hutchic** [comment]
If this is the PR in question https://github.com/Mashape/unirest-python/pull/26 it looks like it did get included https://github.com/Mashape/unirest-python/commit/e8e3b2de1e16cf689d65ee63682be9015ccabbf0

**Comment by vshivam** [comment]
Hadn't noticed. Thanks!

**Comment by hutchic** [comment]
:+1:
