### ISSUE TITLE
HTTP Basic Auth - sending username but no password triggers exception

### ISSUE THREAD

**Issue by philipithomas** [Mashape/unirest-python#38]
Reported on our repo here: https://github.com/Staffjoy/suite/issues/3

We send an API key as an HTTP basic username without a password, e.g. `curl --user API_KEY: http://app.local`. This appears to throw the following error on python 2.7 with unirest 1.1.7:

```
Traceback (most recent call last):
  File "/opt/python/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/python/2.7.12/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/unirest/__init__.py", line 82, in __request
    encoded_string = base64.b64encode(user + ':' + password)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by Marlysson** [comment]
You solved this error?
