### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by DavidLeifer** [Mashape/unirest-python#42]
Collecting unirest
  Using cached Unirest-1.1.7.tar.gz
Collecting poster>=0.8.1 (from unirest)
  Using cached poster-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pz/1xjq35vn19sfkfhtdjljm_5r0000gn/T/pip-build-44zlbnol/poster/setup.py", line 2, in <module>
        import poster
      File "/private/var/folders/pz/1xjq35vn19sfkfhtdjljm_5r0000gn/T/pip-build-44zlbnol/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/private/var/folders/pz/1xjq35vn19sfkfhtdjljm_5r0000gn/T/pip-build-44zlbnol/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/pz/1xjq35vn19sfkfhtdjljm_5r0000gn/T/pip-build-44zlbnol/poster/

I've tried installing from source, what gives?

**Comment by Fomchenkov** [comment]
I also have this problem.

**Comment by joedborg** [comment]
This is because the library is only Python 2 compatible

**Comment by Fomchenkov** [comment]
Which analog libraries supports Python 3?

**Comment by ryanakuhl** [comment]
Devastating!

**Comment by tirkarthi** [comment]
This is due to the syntax being invalid in Python 3 in one of the dependecies. I have made a fork compatible with Python 3 at https://github.com/tirkarthi/unirest-python . You can use it as a git based dependency. It doesn't work for gzip based files for now.

The incompatible dependency is poster. You can find a Python 3 fork at https://github.com/tirkarthi/python-poster

**Comment by hellais** [comment]
I also ran into this issue. Are there plans to add python3 support to this library?

@tirkarthi maybe you want to open a PR to upstream your fixes?

**Comment by wosiu** [comment]
@tirkarthi Thanks! Works like a charm

**Comment by AliYar-Khan** [comment]
> This is due to the syntax being invalid in Python 3 in one of the dependecies. I have made a fork compatible with Python 3 at https://github.com/tirkarthi/unirest-python . You can use it as a git based dependency. It doesn't work for gzip based files for now.
> 
> The incompatible dependency is poster. You can find a Python 3 fork at https://github.com/tirkarthi/python-poster

that work ... thanks man !

**Comment by Ramalingam5g** [comment]
@tirkarthi please say step by step process..
